### ISSUE TITLE
Python 3.10 issue with `collections.Mapping`

### ISSUE THREAD

**Issue by wpol-psiq** [qpic/qpic#12]
For users on Python 3.10, when trying to compile and render some circuits, one gets an attribute error:
```python
AttributeError: module 'collections' has no attribute 'Mapping'
```
As of 3.3 there has been a warning that `collections.Mapping` [would be deprecated in 3.10](https://stackoverflow.com/questions/70195545/module-collections-has-no-attribute-mapping-issue-on-macos-for-sdk-installa) in favor of `collections.abc.Mapping`.

Perhaps there should be a fix to this in `qpic.py` where `collections.Mapping` is called (lines `2395` and `2396`) that checks for Python version? Or at the very least, offer a warning message/add a statement in the `read.me` that using qpic with Python 3.10 may not work?

**Comment by SmoothDragon** [comment]
This is a change that we will make. QPIC is designed to be compatible from Python 2 up to the latest Python 3.

**Comment by SmoothDragon** [comment]
Updated: collections.Mapping -> collections.abc.Mapping

**Comment by king-p3nguin** [comment]
Hi @SmoothDragon, I just noticed that this `AttributeError`  is already fixed in this repo but not deployed to PyPI. Could you update the package in PyPI? Thank you!
