### ISSUE TITLE
Support born/die-in-gate wires

### ISSUE THREAD

**Issue by sammorley-short** [qpic/qpic#13]
To faithfully represent a circuit I have in QPIC, I would like to be able to do something like the following:

![Screenshot 2022-11-15 at 18 24 54](https://user-images.githubusercontent.com/20857520/201997244-937dd5bb-e42a-4b80-b906-9b0d309280c3.png)

In particular, note that there is no wire entering A or exiting B, thereby indicating that the wire is "born" in A and "dies" in B.

Is there a way to do this in QPIC at present? I couldn't see anything in the documentation when I looked recently.

If not, would this be possible to add?

Thanks in advance for your help!

**Comment by SmoothDragon** [comment]
QPIC can get you most of the way there. You can play with TikZ to finish off the job. This was part of our design philosophy. It is too much to include all of TikZ within QPIC, but you can use QPIC to quickly create the layout you want and then tweak the TikZ to get the final tweaks that you want to do.

For your image I start with the simple QPIC code:
```
a W type=owire
a:qwire G A width=25 height=25
a G {x}
a:owire G B width=25 height=25
```
Note that `a G x` refers to a special square box gate with an "x" in it, so we have to specify `a G {x}` instead. This gives us a pretty good approximation to your picture.

![dieingate](https://user-images.githubusercontent.com/11061466/202036835-c9392c28-ac0c-4e0f-b4f2-ed89804b0116.png)

To get it the rest of the way, we can edit the TikZ output. If multiple people really need a particular feature, we will consider adding it, but we don't usually do one off modifications.

To get the `x` in the center without the box around it, let's make the `x` box skinnier with `width=5` and look at the TikZ.

```
a W type=owire
a:qwire G A width=25 height=25
a G {x} width=5
a:owire G B width=25 height=25
```

Which results in
![dieingate](https://user-images.githubusercontent.com/11061466/202037608-8855b4d2-1803-4651-b6df-c87088bf49b4.png)

which has the following TikZ.
```
\begin{tikzpicture}[scale=1.000000,x=1pt,y=1pt]
\filldraw[color=white] (0.000000, -7.500000) rectangle (91.000000, 7.500000);
% Drawing wires
% Line 1: a W type=owire
\draw[color=black] (18.500000,0.000000) -- (72.500000,0.000000);
% Done with wires; drawing gates
% Line 2: a:qwire G A width=25 height=25
\begin{scope}
\draw[fill=white] (18.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
\clip (18.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
\draw (18.500000, -0.000000) node {A};
\end{scope}
% Line 3: a G {x} width=5
\begin{scope}
\draw[fill=white] (45.500000, -0.000000) +(-45.000000:3.535534pt and 8.485281pt) -- +(45.000000:3.535534pt and 8.485281pt) -- +(135.000000:3.535534pt and 8.485281pt) -- +(225.000000:3.535534pt and 8.485281pt) -- cycle;
\clip (45.500000, -0.000000) +(-45.000000:3.535534pt and 8.485281pt) -- +(45.000000:3.535534pt and 8.485281pt) -- +(135.000000:3.535534pt and 8.485281pt) -- +(225.000000:3.535534pt and 8.485281pt) -- cycle;
\draw (45.500000, -0.000000) node {{x}};
\end{scope}
% Line 4: a:owire G B width=25 height=25
\begin{scope}
\draw[fill=white] (72.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
\clip (72.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
\draw (72.500000, -0.000000) node {B};
\end{scope}
% Done with gates; drawing ending labels
% Done with ending labels; drawing cut lines and comments
% Done with comments
\end{tikzpicture}
```

To make the box invisible, we change the line
```
\draw[fill=white] (72.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
```
to the line
```
\path[draw=none,fill=white] (72.500000, -0.000000) +(-45.000000:17.677670pt and 17.677670pt) -- +(45.000000:17.677670pt and 17.677670pt) -- +(135.000000:17.677670pt and 17.677670pt) -- +(225.000000:17.677670pt and 17.677670pt) -- cycle;
```

This then results in the following graphic:
![text](https://user-images.githubusercontent.com/11061466/202038462-a5ea6c76-b3bc-4635-a0c7-2e2f7bc05904.png)

Rounding the corners is something else that can be done in TikZ, and a box with rounded corners might be something good to add to QPIC, so we will discuss it.

**Comment by sammorley-short** [comment]
Great, thanks! I'm not too bothered about the specifics of the rendering style, but rather the ability to "birth" and "kill" wires in boxes, so the use of `owire` is perfect here. 

Just a suggestion, but you might want to consider adding an example for how to use this in something like the above. Currently the use of `owire` is restricted to creating control elbows and in the pacmac example. Hence when looking through the example images, I couldn't find an example of the feature I wanted. Adding this might save others asking the same question 🙂 

Also, out of interest, why would you need to use `a G {x}` + TikZ hacking to get the label as displayed inline on the wire? Wouldn't something like `LABEL x` work?

**Comment by SmoothDragon** [comment]
You are absolutely right that `a LABEL x` would work. However the spacing is wider and I was trying to mimic how close the wires came to `x` in your example diagram. You should be able to modify generated by `a LABEL x` and modify the TikZ to close the distance as well. Thank you for pointing this option out. There are multiple ways to solve many of these problems.

We will look into adding more examples. That is a very handy way to get people started.
