### ISSUE TITLE
PyPI has an outdated version of the package

### ISSUE THREAD

**Issue by Kirs67** [qpic/qpic#14]
PyPI still contains the version 1.0.2: [https://pypi.org/project/qpic/](url)
while the version 1.0.3 was already released, including a very important fix that adresses the deprecation of collections.Mapping; therefore, the PyPI version is not compatible with Python 3.10+.
Please, update the package on PyPI PyPI

**Comment by SmoothDragon** [comment]
Thank you for the bump. I should have it pushed shortly.

**Comment by SmoothDragon** [comment]
Sorry for the delay. The new PyPI package has been pushed.
