### ISSUE TITLE
How should I run the commands?

### ISSUE THREAD

**Issue by jiawei-wu96** [qpic/qpic#15]
Sorry, I'm new to python. This might be a stupid question. 

 I have installed qpic through pip with the following command:
`pip install qpic`
and it is successful.

The mannul says the basic usage is: 
`qpic diagram.qpic`
But where should I run this command?

When I tried to run this command in powershell, the error shows 
`"qpic" is not recognized as a  name of cmdlet, function, script file, or operable program`

I guess this is because powershell cannot find the path of qpic, so I managed to find out the installation location at somewhere named ".../site-packages/qpic", where there are qpic.py and makefile, add the path to system environment. but it still does not work.

When I ran this command in python, the error shows: 
`SyntaxError: invalid syntax`

Thank you!

**Comment by jiawei-wu96** [comment]
I tried to copy the files qpic.py, __init__.py, __main__.py to my working folder, and run 

`python -m qpic diagram.qpic`

in powershell, then powershell asks me to provide input for qpic from keyboard. the file diagram.qpic seems to be ignored

**Comment by SmoothDragon** [comment]
I usually run on Linux, but let me see if I can track down how to do it in Powershell.

When you are running on the command line in Linux (or Mac), you need to pipe the file into qpic with "<":
`python -m qpic < diagram.qpic`

It looks like the equivalent in Powershell is:
`Get-Content diagram.qpic | python -m qpic`

Try that out and let me know if it works. If you want to put the output in another file, try
`Get-Content diagram.qpic | python -m qpic > diagram.tikz`

**Comment by jiawei-wu96** [comment]
> It looks like the equivalent in Powershell is: `Get-Content diagram.qpic | python -m qpic`
> 
> Try that out and let me know if it works. If you want to put the output in another file, try `Get-Content diagram.qpic | python -m qpic > diagram.tikz`

That works perfectly in powershell. Thank you a lot!
