### ISSUE TITLE
Ellipsis in time direction in qpic

### ISSUE THREAD

**Issue by streawkceur** [qpic/qpic#2]
This looks like a very useful program! I want to indicate in a circuit that I repeat a certain construction an arbitrary number of times, for example using ellipsis - I would like to draw a circuit like [this one](https://upload.wikimedia.org/wikipedia/commons/6/6b/Shor%27s_algorithm.svg). What is the recommended way to do this in qpic? If I just put a line `o:type=owire` to make a wire disappear for some time, a filled dot appears at its end.

Thank you for your work.

**Comment by streawkceur** [comment]
I found the solution. It is to use the line `LABEL ...`.

I didn't find this out from skimming the documentation (although it is written in there, which I found out afterwards), but by generating a PDF from all the test cases and looking at the result. To make the stuff clearer to people like me who can't read ("A picture is worth approximately a thousand words"), I think it would be helpful if you add a PDF with the test cases to the repository.

**Comment by SmoothDragon** [comment]
There are a number of sample diagrams in qpic/tests/data. The modular exponentiation diagram (ModExp.qpic) is very similar to what you want. I am attaching the PDF for you to look at easily.
[ModExp.pdf](https://github.com/qpic/qpic/files/230366/ModExp.pdf)
