### ISSUE TITLE
Change to classical wire without measurement icon

### ISSUE THREAD

**Issue by sebastianv89** [qpic/qpic#3]
First of all: love this tool, thank you for making this.

I am drawing a circuit in which I want to let a classical wire start from a certain gate. When I try this, a measurement icon is drawn on top of the gate.  This small example illustrates the issue:

```
a W
b W owire

b G U b:cwire
+a b
```

I get this:
![small](https://cloud.githubusercontent.com/assets/3017046/21324712/ed06c430-c5f0-11e6-9c2e-8852ba5e097c.png)
instead of the gate U. Is it possible to do what I want?

**Comment by KutinS** [comment]
qpic is trying to override you here -- it figures the only way to change to a cwire is to measure.

This worked for me:

a W
b W cwire

b START width=0 ; b G U
+a b

So here b is classical, but it doesn't start until you ask it to.  The semicolon makes sure the start happens together with the U, and the width=0 makes sure it doesn't take up any space.

[Sebastian.pdf](https://github.com/qpic/qpic/files/662643/Sebastian.pdf)

![sebastian](https://cloud.githubusercontent.com/assets/11061466/21362212/9eeb34a2-c6a4-11e6-9f1e-b3ab5186122f.png)

**Comment by sebastianv89** [comment]
Clever solution, works for me. Thank you!
