### ISSUE TITLE
Trouble Running qpic on Windows 7

### ISSUE THREAD

**Issue by dmarciano** [qpic/qpic#4]
Good Morning,

I've read through the documentation and would love to use the program, but I'm haveing trouble running it on Windows (Window 7 Ultimate x64).  I'm pretty sure it is probably something I'm doing wrong (as I'm not familiar with Python) but I couldn't find an answer in any of the documentation.

I installed Python 3.6.1 and allowed it to add its information to the environmental (user) variable PATH (the value that was saved is "C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Dominick\AppData\Local\Programs\Python\Python36\").  I was also able to use the `pip install qpic` command without any issue.  I downloaded the **qpic.py** file and saved it in my programming folder.  Finally, to use as a test, I copied the code for the *Decorated quantum teleportation circuit* (on the homepage of qpic) and saved it as a file named **test.qpic**.

I wanted the output to be a PNG file so in the command prompt I used the command `python qpic.py test.qpic -o test.png` (the current directory was set to the programming folder where the **qpic.py** and **test.qpic** files are located).  The program seems to be running but nothing happens and no PNG file is created.  I left it running for a good 5 minutes because canceling it using **Ctrl-C**.  When I did that, I got the following message:

```
Traceback (most recent call last)`
   File "qpic.py", line 2896, in <module>
      main()
   File "qpic.py", line 2887, in main
      for (words, line_options, gate_options, comment0, comment1) in get_command_from_file(infile):
   File "qpic.py", line 2626, in get_command_from_file
      for line in in_file:
KeyboardInterrupt
```

I also tried changing the current directory to where Python is installed (C:\Users\Dominick\AppData\Local\Programs\Python\Python36) and run the command `python Scripts\qpic C:\Users\Dominick\Desktop\Programming\qpic\test.qpic -o test.png` but this resulted in the following message:

```
tikz2preview test.tikz
Traceback (most recent call last):
  File "Scripts\qpic", line 167, in <module>
    main()
  File "Scripts\qpic", line 164, in main
    qpic_args(args)
  File "Scripts\qpic", line 155, in qpic_args
    if ExecuteShellFunctions(args):
  File "Scripts\qpic", line 103, in ExecuteShellFunctions
    tikz = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
  File "C:\Users\Dominick\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Dominick\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I'm not sure which file it is unable to find.  There is a file call **qpic** (without any extension) in C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Scripts and I also confirmed that the **subprocess.py** file is in the C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Lib folder.

I'm not sure what else to try.  Any help you can provide would be greatly appreciated.  I would really love to use this application to make some circuits for a series of articles I'm writting.  If you need any further information, please let me know.

Thank You

**Comment by SmoothDragon** [comment]
Conversion to PNG uses the ImageMagick program **convert**. A Windows version is available at https://www.imagemagick.org/script/download.php. I have not tried using **qpic** with **convert** on Windows.

Since **qpic** creates the PNG file from a PDF file, I would first verify that **qpic** can run **pdflatex** by `python qpic.py test.qpic -o test.pdf`. If that fails, you will need to install **pdflatex** as well. If that works, but ImageMagick is difficult to install, you may consider using another program to convert the PDF file to PNG manually.

**Comment by dmarciano** [comment]
Thank you for the quick response.  I tried outputting to PDF but that failed as well.  I looked into installing pdflatex, but from what I found it seems that it is not something that can be installed by itself - it is a component for a larger TeX system.  I decided to go ahead and download the ProTeXt installation which is supposed to install pdflatex as well.  I will let you know if I experience any further issues after installing pdflatex and and ImageMagick.

**Comment by SmoothDragon** [comment]
**qpic** does not require any other dependency to generate **LaTeX** code. Your easiest solution may be to generate the  **LaTeX** code with **qpic**, compile that into a PDF using ProTeXt or some other LaTeX compatible program and then finally convert the PDF to PNG using another utility. I don't use Windows myself, so I'm not sure how hard it is to script everything together. Please let me know what you end up doing and if I can help in any other way.

**Comment by dmarciano** [comment]
Good Morning,

So I went ahead and installed ProTeXt which installed MiKTex and TeXstudio.  I searched the MikTex installation folder for **pdflatex** and found multiple files (e.g. **pdflatex.exe** and **miktex-pdflatex.exe**) and I also confirmed that TeXstudio found **pdflatex**.  So I went ahead and tried to run `python qpic.py test.qpic -o test.pdf` from the command prompt with the current directory set to the folder where **qpic.py** and **test.qpic** are both saved.  However the same issue occurred.  The command prompt just hanged and when I interrupted the work using **Ctrl-C** I got the following message:

```
Traceback (most recent call last):
  File "qpic.py", line 2896, in <module>
    main()
  File "qpic.py", line 2887, in main
    for (words, line_options, gate_options, comment0, comment1) in get_command_from_file(infile):
  File "qpic.py", line 2626, in get_command_from_file
    for line in in_file:
KeyboardInterrupt
```

Is it possible I'm not letting it run long enough?  How long should it take (approximately) for the PDF to be created?  Also, could it be a problem that I didn't install MiKTeX in the default folder?  It originally wanted to install it in the C:\Users\Dominick\AppData folder but I changed this to C:\Program Files?

Thank You

**Comment by KutinS** [comment]
Thanks for your interest and for the detailed reports.  I have no real experience with TeX in a Windows environment.

Your traceback suggests that qpic.py isn't actually reading the input file test.qpic -- it's stuck in the main loop, possibly waiting for input from stdin.  You might want to try changing "test.qpic" to "< test.qpic" on your command line.

The real question is _why_ this is happening, and I'm not sure.  I'll see if I can figure anything out.

**Comment by dmarciano** [comment]
@KutinS 

Thank you for the suggestion.  I just ran the command `python qpic.py < test.qpic -o test.pdf` and it output the LaTeX code instead of creating the PDF.  Below is a example of the first few lines that were written in the command window:

```
\providecommand{\K}[1]{\left|#1\right\rangle}
\begin{tikzpicture}[scale=1.000000,x=1pt,y=1pt]
\filldraw[color=white] (7.500000, 0.000000) rectangle (-82.500000, -198.000000);

% Drawing wires
% Line 2: a  W \K{\phi} [x]
\draw[color=black] (-75.000000,0.000000) -- (-75.000000,-123.000000);
\draw[color=black,rounded corners=4.000000pt] (-74.500000,-123.000000) -- (-74.5
00000,-141.000000) -- (-52.000000,-148.500000);
\draw[color=black,rounded corners=4.000000pt] (-75.500000,-123.000000) -- (-75.5
00000,-141.000000) -- (-53.000000,-148.500000);
\draw[color=black,rounded corners=4.000000pt] (-52.000000,-148.500000) -- (-29.5
00000,-156.000000) -- (-29.500000,-198.000000);
\draw[color=black,rounded corners=4.000000pt] (-53.000000,-148.500000) -- (-30.5
00000,-156.000000) -- (-30.500000,-198.000000);
```

So it seems that adding the `<` at least allowed the **qpic.py** script to get the file, but it is still not output any file type.  I have tried generating a PDF using both the `-f` and `-o` commands (I also tried both the short and long forms of each command) and I also tried adding `<` before the command at various placed (e.g. at the end of the command, between **qpic.py** and **test.qpic**, etc.).

If I can't get it to output to a file, does that mean I'll have to copy the LaTeX code and manually enter it into TeXstudion (which is the LaTeX editor I'm using)?  My only concern with this is that if the circuit is large, and the LaTeX code long, it may prevent me from copying all the code.  Windows command prompt has a maximum number of row you can scroll back.  After a certain point, if the script keeps outputting lines of LaTeX code, the earlier lines will be lost.

**Comment by SmoothDragon** [comment]
I should have seen this earlier. **qpic.py** is the executable that produces the LaTeX code, nothing more. The executable **qpic** is a script that tries to call other programs on the output of **qpic.py** to make a PDF or PNG file. **qpic.py** cannot create your PDF or PNG file.

I believe that if you `pip install qpic`, you should be able to use **qpic** from the command line. If **pdflatex** and **convert** are also available from the command line then `qpic -f png test.qpic` should generate your PNG file. If you only have **pdflatex** installed, then `qpic -f pdf test.qpic` should give you a PDF that you make be able to convert via other means.

**Comment by dmarciano** [comment]
I did do the installation using `pip install qpic`, however **qpic** is not available from the command; **pdflatex** is though.

So in the command prompt window, I change the current directory to the folder where the **qpic** file is located, which is C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Scripts while the **test.qpic** file is located in the folder C:\Users\Dominick\Desktop\Programming\qpic.  However I am still getting an error message.  I tried the following commands:

```
python qpic -f pdf C:\Users\Dominick\Desktop\Programming\qpic\test.qpic
python qpic -f pdf "C:\Users\Dominick\Desktop\Programming\qpic\test.qpic"
```

Then I copied the **test.qpic** file into the same folder as the **qpic** file and tried the following commands:

```
python qpic -f pdf test.qpic
python qpic -f pdf < test.qpic
```

However, in every case the following error message was returned:

```
tikz2preview texput.tikz
Traceback (most recent call last):
  File "qpic", line 167, in <module>
    main()
  File "qpic", line 164, in main
    qpic_args(args)
  File "qpic", line 155, in qpic_args
    if ExecuteShellFunctions(args):
  File "qpic", line 103, in ExecuteShellFunctions
    tikz = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
  File "C:\Users\Dominick\AppData\Local\Programs\Python\Python36\lib\subprocess.
py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Dominick\AppData\Local\Programs\Python\Python36\lib\subprocess.
py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
Not sure what file it can't find.  I've been able to get a PDF created, but I needed to copy the LaTeX code into TeXstudio, add some additional tags (for the beginning and end of the document) and then build the PDF from that.

As a side note, I found that to output the LaTeX code of a **.qpic** file to another file you can use the following command in the command prompt window: `python qpic.py < basic.qpic > basic_text.tex'

**Comment by SmoothDragon** [comment]
So if **qpic** is not available from the command line after `pip install qpic`, you probably don't have your python script directories added to your **PATH**. Step 3 of the following website shows how you change your PATH variable in Windows 7, but you will need to change the directory names to match those of your installation: http://www.anthonydebarros.com/2011/10/15/setting-up-python-in-windows-7/

The error message you are getting indicates that **qpic** cannot find the file `texput.tikz` or `test.tikz`  (depending on if you are using the `<` or not). The code is testing the filename against `<stdin>` which maybe has a different name under Windows. It also may be that you don't have permission to create files in the python script directory.

I cannot totally recreate your conditions, but running `python qpic -f pdf test.qpic` also causes me issues. Try running `qpic test.qpic` (no `python`) from the `test.qpic` directory after you have added `C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Scripts` to your PATH. If that works, then try `qpic -f pdf test.qpic`, which will hopefully pick up your **pdflatex** executable.

**Comment by dmarciano** [comment]
The python script directory is include in the PATH variable.  The begin of the variable is:

C:\Users\Dominick\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Dominick\AppData\Local\Programs\Python\Python36\;

I cannot run `qpic` from the command prompt without including `python`.  It gives me an error message that qpic is not recognized as an internal or external command, operable program or batch file.  However, if I run `python qpic test.qpic` then the LaTeX code is outputted to the command window.  I can use the command `python qpic testqpic > test.txt` to have the LaTeX code written to a text file in the same folder.

I tried doing this and then changing the extension from `.txt` to `.tikz` and then running `python qpic -f pdf test.qpic` but I am still getting the error message about the system not being able to find the file specified, even though the **test.qpic** and **test.tikz** files are both in the same folder.

This is very frustrating.  For now I will do it the long way of manually copying the LaTeX code into TeXstudio and generating the PDF/PNG file that way, but it would be really nice if this could be made to work smoothly on Windows.  I do appreciate all the help so far though.

**Comment by SmoothDragon** [comment]
I'm out of ideas at this point. I think it is necessary to understand the command line differences between Linux and Windows to proceed further. Please let me know if you figure out how to make it run end to end on Windows 7.

**Comment by peendebak** [comment]
@dmarciano @SmoothDragon @KutinS The issue seems to be that windows cannot execute the tikz2preview script. That script starts with the line `#!/usr/bin/env python`, but that doesn't work for windows.

I could get further by changing the file `qpic` on line 101 to:
```
    command = r'python c:\svn\qpic\bin\tikz2preview %s' % (args.basename + '.tikz')
``` 
The script then fails because `gswin32c.exe` is not available. This can be installed from https://www.ghostscript.com/download/gsdnld.html. The `qpic` then generated a rendered circuit diagram (png output). Miktex was already installed on my system.

Would be nice of the windows side of the package could be cleaned up with this info.

**Comment by gtaifu** [comment]
I have suffered from exactly the same problem as described by @dmarciano , and I found I cannot get the command qpic in my PowerShell terminal. Addressing the first problem, @peendebak provided the solution. To summarize, I use the following steps to get it working on my Windows 7 PC:
- Install qpic using `pip install qpic`. If any dependent package is missing or out-dated, simply install them or upgrade them.
  + After the first step, I get qpic in the location `<path_to_anaconda3>\script\qpic`. This is because I get my Python3 using Anaconda.
- Then modify line 101 of the file `<path_to_anaconda3>\Scripts\qpic`. But the new line should be:
```
 command = r'python <path_to_anaconda3>\Scripts\tikz2preview %s' % (args.basename + '.tikz')
```
  + you should replace `<path_to_anaconda3>\Scripts\tikz2preview`  to the path on your system.
  + After this step is done, I still cannot invoke qpic command in my terminal though the path `<path_to_anaconda3>\Scripts\` is indeed in my system path.
- I use PowerShell profile to solve this problem. I created a new function in my PowerShell profile:
```PowerShell
function qpic () {
python "<path_to_anaconda3>\Scripts\qpic" $args
}
```
  + After this step is done, I can simply type `qpic <qpic_filename>` to generate the .tex file.
  + It can also include all other parameters of qpic.

This provides me a solution to get qpic working on my PC at this moment.

**Comment by rayonde** [comment]
I  find a new way to solve this problem based on the method of @gtaifu .

- After the first two steps of installation using `pip install qpic` and the modification of line 101, we can copy the file `qpic` and append a filename extension `.py` as alone script (I don't know why this file in ` <path_to_anaconda3>\Scripts` has no filename extension, maybe this is exactly the bug). 
- Then we are allowed to copy this `qpic.py` into the same folder as those files `.qpic` we have written.
 (The original file in ` <path_to_anaconda3>\Scripts` seems to not need to change the filename extension)
- Finally, in Anaconda Prompt and under the file path, run `python qpic.py your_file.qpic > your_file.tex`. It works successfully!

Thanks! @gtaifu I was very fortunate that you have proposed a solution two days before I was in trouble. 
I am not a skilled programmer to completely debug :)

**Comment by SmoothDragon** [comment]
qpic version 1.1.0 now uses `__main__.py`.
This allows `python -m qpic < filename.qpic` to work.

I believe this solves your path problem.
