### ISSUE TITLE
Trouble creating the brace for combining qubit states 

### ISSUE THREAD

**Issue by eshaspark** [qpic/qpic#7]
Hello,

I am using the code sample for teleportation ( |\beta_{00}\rangle< ), however the brace for combining multiple qubit states does not work. On the other hand, a bold line appears instead of the curly brace.

**Comment by eshaswaroop** [comment]
<img width="373" alt="Screenshot 2020-03-17 at 5 37 55 PM" src="https://user-images.githubusercontent.com/8880428/76904333-225a6300-6876-11ea-90ab-c98868e42ca3.png">

**Comment by eshaspark** [comment]
The output is 
<img width="373" alt="Screenshot 2020-03-17 at 5 37 55 PM" src="https://user-images.githubusercontent.com/8880428/76904365-33a36f80-6876-11ea-9e17-bad5a008f3ff.png">

instead of 
<img width="373" alt="Screenshot 2020-03-17 at 5 39 59 PM" src="https://user-images.githubusercontent.com/8880428/76904435-57ff4c00-6876-11ea-8e8a-a50645d82777.png">

**Comment by SmoothDragon** [comment]
I just ran the code and I got the brace on the left instead of the bar. Do you mind sending the complete QPIC file you are compiling?

**Comment by SmoothDragon** [comment]
I know you are trying to compile the text from the example, but I am wondering if there is a spurious space in your file. QPIC is very sensitive to spaces.

**Comment by eshaspark** [comment]
I tried again, rewriting the file and being mindful of spaces. But I'm getting the same error.
I am uploading the file here, although I am changing the type to .txt from .qpic since GitHub supports uploads of only certain formats -
[abcd.txt](https://github.com/qpic/qpic/files/4346873/abcd.txt)

I uninstalled qpic and reinstalled as well, but the error stays

**Comment by SmoothDragon** [comment]
So your text file works for me. The next step is to check your TeX installation. After running QPIC and tikz2preview, I get the following TeX file:
[abcd.tex.txt](https://github.com/qpic/qpic/files/4347253/abcd.tex.txt)

Try compiling that with pdflatex. If you are getting the same TeX file as me, but the problem still persists you may be missing a package in your LaTeX installation.

Also, most of our testing was done with pdflatex. If you are going to a DVI file with normal latex, there might be some issues we are unaware of. There are slight differences between the way graphics are created in DVI and PDF.

**Comment by eshaspark** [comment]
I've been compiling using the pdflatex compiler, on overleaf online.

I am sharing my .tikz file here instead of the .tex file since overleaf directly produces the graphics for me using the \input{abcd.tikz} command.
[abcd.tikz.txt](https://github.com/qpic/qpic/files/4347394/abcd.tikz.txt)

Could you kindly compare with your .tikz interim file and let me know about the discrepancies?

**Comment by SmoothDragon** [comment]
I just compiled your TikZ file and it worked for me. I am attaching the PDF I created from your TikZ file. Please verify that your PDF viewer doesn't have a problem and that the file looks normal.
[abcd.pdf](https://github.com/qpic/qpic/files/4352823/abcd.pdf)

**Comment by SmoothDragon** [comment]
Also, if you are inputting the .tikz file into your document, make sure you have the following line in your document header after importing tikz:
\usetikzlibrary{decorations.pathreplacing,decorations.pathmorphing}

**Comment by eshaspark** [comment]
this works now! Adding \usetikzlibrary{decorations.pathreplacing,decorations.pathmorphing} made the difference

**Comment by SmoothDragon** [comment]
Glad we could figure it out! I will update the documentation to reflect this solution.

**Comment by eshaspark** [comment]
thanks!
